### ISSUE TITLE
modify bibliographic entry for keywords

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#10]
The bibliographic record for the dynasty dates has been mistakenly applied to all keywords. It should be removed from all keywords *except* the dynasties.
For example--this reference should not appear with "palatial hall": 
![screen shot 2019-01-09 at 1 12 40 pm](https://user-images.githubusercontent.com/25234059/50922672-ae6e3080-1410-11e9-8348-6e7313eb222d.png)

**Comment by wsalesky** [comment]
@millertg a source attribute will have to be added to the date element in each record. If they apply across the board we can do it programmatically, but perhaps @michellemtaylor @davidamichelson can show @millertg how to add a source reference to a TEI element for other use cases as well?

**Comment by millertg** [comment]
Can do this manually if you think that is best--@michellemtaylor made a great video and @davidamichelson is always available for consult.

**Comment by wsalesky** [comment]
@millertg Yes, that is probably best. Thanks!
