### ISSUE TITLE
"time period" and "state" do not validate in dynasty keyword records

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#127]
@wsalesky the time period, state, and bibl are not validating in the "Dynasty" keywords files. I have a screenshot of one example here. Is this a problem? If so, do I need to change the schema? 
![Screen Shot 2020-02-03 at 2 56 20 PM](https://user-images.githubusercontent.com/25234059/73694424-99a8ae80-469d-11ea-8a26-510154a3bb8e.png)

**Comment by wsalesky** [comment]
@dlschwartz this may be a question for you as it is schema related. She is using the Srophe schema. 

@millertg The file can still be loaded into the eXist-db as long as it is well formed XML (all the tags are closed), and there are no empty xml:id attributes. I think those are the only issues that eXist checks for.

**Comment by dlschwartz** [comment]
@wsalesky @millertg, yes, this is a schema customization issue. If you've used a TEI element and you get an error message like: "x" not allowed anywhere, it most likely means you've got a customized schema that has not included that element.
