### ISSUE TITLE
Bibliography page

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#13]
@wsalesky Would it be possible to add a Bibliography page to the site? I think it would be useful to see the entries we use, even outside of Zotero. Thanks!

**Comment by wsalesky** [comment]
@millertg, Yes we can add that. Should take about half an hour. I can have it up by Monday.

**Comment by wsalesky** [comment]
@millertg I'm playing catch up today. I added this page, but have not yet linked to it. You can review it here: https://architecturasinica.org/bibliography.html

**Comment by millertg** [comment]
@wsalesky Thanks! It looks good to me. We have a number of new entries added to our new Architectura Sinica bibliography page on Zotero. I think I sent you an invitation to that page a while back. Have you seen it?

**Comment by wsalesky** [comment]
@millertg Yes. I will run the code to grab the new zotero data.

**Comment by wsalesky** [comment]
@millertg Okay, it should be up to date.

**Comment by wsalesky** [comment]
@millertg Shall I add a link  to this page? If so where would you like it? Along the top nav? Somewhere else?

**Comment by millertg** [comment]
@wsalesky Yes, please. The top nav seems like the most logical place. Question: if the bibliographic display is not clear, is that something I can manipulate in Zotero? It would be good to have titles in italics, for example.

**Comment by wsalesky** [comment]
I would have to add the italics to the bibliographic transformation. Do you want to make a list of changes?

**Comment by millertg** [comment]
Yes, that sounds like a good idea. I am still working out also how to have Chinese characters, transliterated Chinese, and English (where available), so perhaps I can include that also.

**Comment by wsalesky** [comment]
@millertg Finally added this. Sorry for the delay. Please create new issues for bibliographic display changes.
