### ISSUE TITLE
adding bibliographic entry to keywords

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#15]
@wsalesky We are trying to put the bibliographic element into the keywords. They should show the full entry with the footnote, not just the page number (I have only done this with one dynasty, Chen, shown in the screenshot here). But I don't see how to add that to the TEI. Is it a css issue?
<img width="1047" alt="Screen Shot 2019-03-13 at 9 12 41 PM" src="https://user-images.githubusercontent.com/25234059/54328667-cb73db00-45dc-11e9-8c43-712c97d9f885.png">

**Comment by wsalesky** [comment]
Sorry, there was a bug in the display stylesheets. It is fixed now.
