### ISSUE TITLE
Pulling dynasties out of "architectural terminology"

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#16]
@wsalesky Dynasties aren't really "terms", so it seems strange to have them displayed as a Term (see attached). Can we have them listed as a separate category, perhaps underneath "buildings" and "sites"? 
<img width="1047" alt="Screen Shot 2019-03-13 at 9 12 41 PM" src="https://user-images.githubusercontent.com/25234059/54328917-b0559b00-45dd-11e9-8f31-3947bc5f10fb.png">

**Comment by wsalesky** [comment]
@millertg I think there are two issues here? On the keyword page for a Dynasty (https://architecturasinica.org/keyword/Chen), you want the 'Terms' heading changed? To ?

And then on the browse page you want a new category for Dynasties? https://architecturasinica.org/terminology.html

Is that correct?

**Comment by millertg** [comment]
@wsalesky Yes, you are correct. 
1. We need a new category, "period/dynasty/kingdom" on the browse page. 
2. Still trying to figure out how best to indicate that something is a dynasty, kingdom, or period/time span, on the keyword page. Maybe leave this as is for now.
