### ISSUE TITLE
formatting bib page

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#18]
@wsalesky The first entry (1.) on the bibliography page is empty
https://architecturasinica.org/bibliography.html

**Comment by wsalesky** [comment]
@millertg It is this record. It has no title: https://architecturasinica.org/bibl/35BTSX3S

**Comment by millertg** [comment]
@wsalesky I deleted the record, but am having a hard time getting the Zotero update script to run again.

**Comment by wsalesky** [comment]
Okay, can you describe the problems you are running into? Did you get an error, or did it just not delete?

**Comment by millertg** [comment]
it seems to have deleted fine, I just can't get the script to run. It just sits there loading....
![Screen Shot 2019-03-14 at 11 17 25 AM](https://user-images.githubusercontent.com/25234059/54373166-c9e0fc00-464a-11e9-9bde-0df0d71a21b3.png)

**Comment by wsalesky** [comment]
@millertg Just leave it for a while, it takes a long time to run through all the records.

**Comment by wsalesky** [comment]
@millertg If it has not finished in 10 minutes there is a problem and I can take a look.

**Comment by millertg** [comment]
@wsalesky ok, will do

**Comment by millertg** [comment]
Still not working. Do you think this could be an invalid security certificate problem? [cid:0921092D-8405-44C5-8122-82489AAD0730@attlocal.net]

--------------------------------------------
Tracy Miller, Ph.D.
Associate Professor, History of Art and Asian Studies
Vanderbilt University
President, Society for Song, Yuan, and Conquest Dynasty Studies
https://my.vanderbilt.edu/tracymiller/

On Mar 14, 2019, at 11:19 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:

@millertg If it has not finished in 10 minutes there is a problem and I can take a look.

**Comment by wsalesky** [comment]
@millertg This seems to be a problem with settings on the server. I am working on it with our server person and will keep you up to date. If it is urgent I can load the bibliographic data manually.
