### ISSUE TITLE
footnote formatting

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#19]
@wsalesky can we have footnotes in Chicago notes/bibliography style? i.e.: 
Author Given name, Author Surname, _Title_  (Publisher location: Publisher name, date), page number(s).

Except Chinese, in which case: Author Surname Author Given Name Traditional Characters Author Surname Traditional Characters Author Given Name, _Title in pinyin in italics_Title in Traditional Characters (Publisher location: Publisher name, date), page number(s).

e.g. 

Brian Grazer and Charles Fishman, A Curious Mind: The Secret to a Bigger Life (New York: Simon & Schuster, 2015), 12.

![image](https://user-images.githubusercontent.com/25234059/54366302-6c46b280-463e-11e9-969a-f720e50f5de6.png)

Variations for articles, etc., can be found here, but not sure what you need....
https://www-chicagomanualofstyle-org.proxy.library.vanderbilt.edu/tools_citationguide/citation-guide-1.html

**Comment by wsalesky** [comment]
@millertg Okay. It will take me a few days to get to this. By end of the day Monday

**Comment by millertg** [comment]
Thanks!

**Comment by wsalesky** [comment]
@millertg Just getting back to this. Sorry for the lag. If you could give an example record to work with that would be helpful. Link to a building or site with a footnote and how you would expect it to appear, so I have something to check the result against. 
Thanks!

**Comment by millertg** [comment]
Will do. 

Quick question—is there anything that the “Geolocation” does that “Dynamic Site Archive” doesn’t do? Was just questions by a colleague and it seems to me that at this point the “Dynamic Archive” is doing it all. Should we just cut “Geolocation” entirely, because it is redundant?

**Comment by wsalesky** [comment]
No, they are very similar, Geolocation just has a bigger map, and moves the facets into the map as an overlay. I think it is nice to have that big map, but you could have the big map on the Dynamic Site Archive if you want to eliminate the Geolocation menu item.

**Comment by millertg** [comment]
How cumbersome would it be to have a link to the larger map (maybe just something called “larger map”) in the DSA?

**Comment by wsalesky** [comment]
Not a problem. In fact we can just keep that page, and link to it from the DSA page and remove the 'Geolocation' from the main menu. Would that work for you?

**Comment by millertg** [comment]
Sounds perfect—let’s try it!

**Comment by wsalesky** [comment]
Done.

**Comment by millertg** [comment]
Magic! I like it :-).
