### ISSUE TITLE
update script appears to run, but doesn't update

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#196]
We have run the update script several times, but new entries in our Architectura Sinica Zotero library are not updating. I have screenshots from the morning of one example attached. (The Zhongguo mingsheng cidian).
![Screen Shot 2020-04-24 at 9 07 48 AM](https://user-images.githubusercontent.com/25234059/80221777-62e29480-860b-11ea-9cb2-e2925c67007c.png)
![Screen Shot 2020-04-24 at 9 07 08 AM](https://user-images.githubusercontent.com/25234059/80221787-6544ee80-860b-11ea-899c-01ea15d7aa76.png)

**Comment by wsalesky** [comment]
@millertg Can you add a link to the Architectura Sinica page? So I can check?

**Comment by wsalesky** [comment]
This has been resolved
