### ISSUE TITLE
change source for "date slider" dates

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#22]
The "date slider" is pulling its dates from the "site" files. Can that be changed so they pull from the "building" files? The individual buildings have a narrower historic range, which I think will give a better result.

**Comment by wsalesky** [comment]
@millertg I updated it, is this better?

**Comment by millertg** [comment]
@wsalesky unfortunately not. On the "research tool" I am still seeing a list of sites, not a list of buildings.

**Comment by wsalesky** [comment]
Can you give me a link to a building that has a more specific date than the site? So I can do some targeted testing?

**Comment by millertg** [comment]
Sure--Baoguosi is a good example. It was founded in the Eastern Han (25-220 CE) https://architecturasinica.org/place/000004, but the earliest historic building is from 1013 https://architecturasinica.org/place/000132. 
I just tried to update this, btw, and it doesn't seem to be loading...

**Comment by wsalesky** [comment]
@millertg I updated it, is this any better?

**Comment by millertg** [comment]
Much better!  Thank you.

tm

Sent from my iPhone

On Mar 21, 2019, at 7:53 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


@millertg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmillertg&data=02%7C01%7Ctracy.g.miller%40vanderbilt.edu%7C06f74ce3cd454740cff108d6ae049b37%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636887732139106583&sdata=cBngsCZ9V9TY8TGoF960JGYTc99BXE19mY2ENbYI2zg%3D&reserved=0> I updated it, is this any better?

**Comment by wsalesky** [comment]
Great!
