### ISSUE TITLE
note text not displaying with images

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#23]
For records like pingzhu the image now shows, but I don't see any of the note text or bib. Text is in the tei, however. 
<img width="1046" alt="Screen Shot 2019-04-07 at 9 41 55 AM" src="https://user-images.githubusercontent.com/25234059/55686788-6a5cd000-591a-11e9-8548-c75c3b0b5cce.png">

**Comment by wsalesky** [comment]
Fixed.

**Comment by millertg** [comment]
Thank you!
