### ISSUE TITLE
remove display of irrelevant search categories

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#24]
@wsalesky  In architectural terminology, the list of categories on the left should filter out those categories with zero results when a "search category" is selected. For example, if I select architectural features from the list of search categories, the result shows the architectural features, but also includes the other categories with (0) values. Is there a way to not display that category at all if it is a (0) value?
<img width="856" alt="Screen Shot 2019-04-12 at 8 28 05 PM" src="https://user-images.githubusercontent.com/25234059/56061502-85d43a80-5d61-11e9-855f-a1a99cf9494e.png">

**Comment by wsalesky** [comment]
Fixed

**Comment by wsalesky** [comment]
Done.
