### ISSUE TITLE
note field displayed twice for cao?

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#25]
@wsalesky Looking at the "cao" entry in architectural features, I see that the note field is displayed twice. My colleague Chris Benda has added to that entry, but in the TEI, I couldn't find why it would display a duplicate. Can you figure this out? 
<img width="839" alt="Screen Shot 2019-04-12 at 8 17 35 PM" src="https://user-images.githubusercontent.com/25234059/56063858-5d037380-5d68-11e9-87bc-ece55adc5ffa.png">

**Comment by wsalesky** [comment]
Fixed.
