### ISSUE TITLE
"hamburger" menu icon does't show links on MacBook or iphone

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#26]
@wsalesky I don't see a list when I click on the collapsable menu icon. I think this may be a Mac issue, but am not sure how to test/fix it. It is particularly problematic on the iphone because it is the only menu bar for the small screen.
<img width="161" alt="Screen Shot 2019-04-15 at 9 58 10 AM" src="https://user-images.githubusercontent.com/25234059/56120032-2e062100-5f65-11e9-808b-07409d4ee49b.png">

**Comment by wsalesky** [comment]
fixed.

**Comment by millertg** [comment]
Yay—thanks!!
Quick question—is that menu pulled from a different location than the top menu bar? I need to change Digital Research Tool to Dynamic Site Archive wherever it occurs. Sounds more.... dynamic :-)

Thanks again!

tm

Sent from my iPhone

On Apr 15, 2019, at 1:58 PM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


fixed.

**Comment by wsalesky** [comment]
Same place, it is one menu, displayed differently for different screen sizes.
