### ISSUE TITLE
Add support for TEI:listbibl in Srophe "footnote" sections

### ISSUE THREAD

**Issue by davidamichelson** [VandyVRC/tcadrt#35]
We would like to add support for the TEI:listbibl element to function the same way as TEI:bibl currently functions for sources/footnotes in individual documents.

Thus currently: ```<bibl xml:id="biblcao-1">``` created footnote #1 based on @source="biblcao-1"

We would like to add support for ```<listBibl xml:id="biblcao-3"><bibl>...</bibl></listBibl>``` to create footnote #3 based on @source="biblcao-3"

The resulting footnote will need to format each citation contained in the TEI:bibl inside the listBibl as a chain of citations separated by semi-colons, but otherwise using the same template for how to render bibl elements into prose.

See example of code here: https://architecturasinica.org/keyword/cao.tei

@dlschwartz what do you think about this?

**Comment by chrisbenda** [comment]
Here's the line we're talking about in the code:  https://github.com/VandyVRC/tcadrt/blob/95a6af9a41cde2ac4b1ebe6928ca006fcea17dca/data/keywords/tei/cao.xml#L96.

**Comment by wsalesky** [comment]
How does this look: 
https://architecturasinica.org/keyword/cao

**Comment by chrisbenda** [comment]
Much better.  Thanks, Winona!
