### ISSUE TITLE
new formatting from Zotero

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#39]
@wsalesky 
Here is a sample of what I see on the entry for "cao" (note two extra zotero links at the end, these are icons on screen--I added a screenshot of this below)
1 Guo, Qinghua. A Visual Dictionary of Chinese Architecture 中國建築英漢雙解辭典. Mulgrave, Vic.: Images, 2002. , pp: 21.Link to Zotero Bibliographic RecordLink to Zotero Bibliographic Record
2 Fu, Xinian. Traditional Chinese Architecture: Twelve Essays. Edited by Nancy Shatzman Steinhardt. Translated by Alexandra Harrer. The Princeton China Series. Princeton, New Jersey: Princeton University Press, 2017. , pp: 350.Link to Zotero Bibliographic RecordLink to Zotero Bibliographic Record

In the note style we were hoping for, they would appear like this: 
GUO, Visual Dictionary, 21. zotero link
FU, Twelve Essays, 350. zotero link

Also--I would like to have the surnames display in all caps. Do I need to enter that into Zotero, or can that be modified programmatically? 

![Screen Shot 2019-05-17 at 2 36 54 PM](https://user-images.githubusercontent.com/25234059/57951937-43969f80-78b1-11e9-9d28-643508310922.png)

**Comment by wsalesky** [comment]
@millertg Please review: https://architecturasinica.org/keyword/cao

**Comment by millertg** [comment]
@wsalesky Wow--that is great! Let me consult with Yuh-Fen and Chris as well to make sure I am not missing something critical.

**Comment by wsalesky** [comment]
@millertg You can close if you are satisfied with the output

**Comment by chrisbenda** [comment]
Sorry -- I'll close this.
