### ISSUE TITLE
external relationships list in keywords--problems with "More"

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#408]
@wsalesky 
the "More" link on the keyword pages does not result in a continuation of the list. After clicking it, entries are repeated, and are not organized in alphabetical order by pinyin title
![Screen Shot 2021-05-25 at 4 55 06 PM](https://user-images.githubusercontent.com/25234059/119574100-ce50e580-bd7a-11eb-8da8-d96a7512c4b4.png)
![Screen Shot 2021-05-25 at 4 54 02 PM](https://user-images.githubusercontent.com/25234059/119574112-d14bd600-bd7a-11eb-929c-242bd03a68b8.png)

**Comment by wsalesky** [comment]
Moved to application. https://github.com/VandyVRC/srophe-eXist-app/issues/200
