### ISSUE TITLE
liang, lan'e (lan e, lane), not showing on main architectural features search page

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#56]
@wsalesky 
we added lan'e and liang to our keywords, but lan'e does not appear in a general keyword search here: 
https://architecturasinica.org/terminology.html (page 2)
<img width="643" alt="Screen Shot 2019-05-23 at 8 38 17 AM" src="https://user-images.githubusercontent.com/25234059/58257229-25f48a80-7d36-11e9-9ae8-efdd8a719453.png">

although you can find it if you limit by architectural feature here: 
https://architecturasinica.org/terminology.html?fq=;fq-Search%20Category:architectural%20features&start=1
![Screen Shot 2019-05-23 at 8 36 49 AM](https://user-images.githubusercontent.com/25234059/58257154-f9d90980-7d35-11e9-9f2b-488b69b6a3b2.png)

would like to fix and know why so we can correct on future entries

**Comment by shubenda** [comment]
Lan’e appears.
It didn’t because I made a mistake.
https://architecturasinica.org/keyword/lane

But it appears after liang, not before.

Yuh-Fen

**Comment by wsalesky** [comment]
@millertg @shubenda This looks like an error in the sort function, it is not correctly normalizing accented characters. I will look into it and get fix out soon.

**Comment by wsalesky** [comment]
Fixed
