### ISSUE TITLE
updating keyword URIs

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#66]
@wsalesky 
We need to update the keyword URIs, but the changes we make to keyword files in oXygen (for stūpa, as an example) are not showing on the website. Can you help?

**Comment by wsalesky** [comment]
@millertg Webhooks were not working. They are working now. Please let me know if you have more issues.

**Comment by chrisbenda** [comment]
Thanks, Winona.  The footnotes I added the other day are now showing up.  (Not sure if this fixes Tracy’s issues, though.)  --Chris

**Comment by wsalesky** [comment]
@chrisbenda can you link to the file you added, and the additions you made? So I can troubleshoot it?

**Comment by chrisbenda** [comment]
Actually, everything is working for me.

**Comment by millertg** [comment]
working now, thanks!
