### ISSUE TITLE
zotero causing crashes?

### ISSUE THREAD

**Issue by millertg** [VandyVRC/tcadrt#67]
@wsalesky many records (cao, caihua, dipan), but not all (die) are returning tomcat errors. I ran the zotero script update last night. Could that have caused the problem?
![Screen Shot 2020-01-13 at 6 09 16 AM](https://user-images.githubusercontent.com/25234059/72255066-6a85ac80-35cb-11ea-8dd2-b6bc99ac13ce.png)

**Comment by wsalesky** [comment]
@millertg Can you tell me what links you were using that gave you those results? I did a search for all of the examples you listed an returned working page:
Example: 
https://architecturasinica.org/search.html?q=dipan
https://architecturasinica.org/keyword/k000018

https://architecturasinica.org/search.html?q=cao
https://architecturasinica.org/keyword/k000005

I suspect there are some bad links (to the old file, since these have been renamed) somewhere that are causing the problem? Also, this 404.html should show different error, so I till fix that as a related, but different issue!

**Comment by millertg** [comment]
@wsalesky Interesting--if I select "All", then I can see the pages. But if I don't, then caihua, cejiao, Chen, chiwei, chu, chuandou, die, dipan, dingfu, Eastern Han and Eastern Jin, all return the 404 error.

**Comment by wsalesky** [comment]
@millertg  Please send me links to the page you are on, and the links you click that give the 404 error so I can reproduce the issue.

**Comment by millertg** [comment]
This is the page I am on: https://architecturasinica.org/terminology.html
I'm not sure how to send you the link for the term that gives me the tomcat error. This is what is visible: https://architecturasinica.org/404.html

When I access them from the All page (https://architecturasinica.org/terminology.html; but showing 101 results)
I receive errors on the below, which I think are all the ones whose URI I have changed. 

https://architecturasinica.org/keyword/k000004
https://architecturasinica.org/keyword/k000006
https://architecturasinica.org/keyword/k000008
https://architecturasinica.org/keyword/k000009
https://architecturasinica.org/keyword/k000010
https://architecturasinica.org/keyword/k000011
https://architecturasinica.org/keyword/k000018
https://architecturasinica.org/keyword/k000019
https://architecturasinica.org/keyword/k000020
https://architecturasinica.org/keyword/k000021

**Comment by millertg** [comment]
BTW, when I click "All" again, after getting 101 results, I get this error: 
https://architecturasinica.org/terminology.html?&perpage=99&start=1&perpage=101
<img width="890" alt="Screen Shot 2020-01-10 at 2 41 47 PM" src="https://user-images.githubusercontent.com/25234059/72276533-be0cf000-35f5-11ea-8b30-0ce44cbd7fba.png">

**Comment by wsalesky** [comment]
@millertg Can you try doing a hard refresh on this page https://architecturasinica.org/terminology.html, and then try the links again?

**Comment by millertg** [comment]
@wsalesky working now!
